---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: ''
  label: Root pages
  create: all
  match: "*"
- type: heading
  label: Content Types
- type: directory
  path: portfolio
  label: Portfolio
  create: documents
  match: "*"
  templates:
  - portfolio-item
- type: directory
  path: service-type
  label: Type of Service
  create: documents
  match: "*"
  templates:
  - service-type
- type: heading
  label: Pages
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "*"
  templates:
  - blog-post
- type: directory
  path: services
  label: Services
  create: documents
  match: "*"
  templates:
  - service
- type: directory
  path: past-work
  label: Past Works
  create: documents
  match: "*"
  templates:
  - portfolio-item
- type: directory
  path: contact
  label: Contact
  create: documents
  match: "*"
  templates:
  - contact
upload_dir: public/static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
